export enum messageTypes {
  CONNECT = "CONNECT",
  LOGIN = "LOGIN",
  CONNECTION_OFFER = "CONNECTION_OFFER",
  CONNECTION_ANSWER = "CONNECTION_ANSWER",
  ICE_CANDIDATE = "ICE_CANDIDATE",
  ERROR = "ERROR",
  UPDATE_USERS = "UPDATE_USERS",
}
